[profile.default]
src = "src"
test = "test"
out = "out"
libs = ["lib"]
solc_version = "0.8.28"
optimizer = true
optimizer_runs = 200
via_ir = true
fs_permissions = [{ access = "read", path = "./" }]

# Remappings for dependencies
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@account-abstraction/contracts/=lib/account-abstraction/contracts/",
    "forge-std/=lib/forge-std/src/",
    "erc4626-tests/=lib/openzeppelin-contracts/lib/erc4626-tests/src/",
    "halmos-cheatcodes/=lib/openzeppelin-contracts/lib/halmos-cheatcodes/src/"
]

# Dependencies - forge install will install all of these automatically
[dependencies]
forge-std = "foundry-rs/forge-std@v1.9.7"
openzeppelin-contracts = "OpenZeppelin/openzeppelin-contracts@v5.3.0"
openzeppelin-contracts-upgradeable = "OpenZeppelin/openzeppelin-contracts-upgradeable@v5.3.0"
account-abstraction = "eth-infinitism/account-abstraction@v0.8.0"
